/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#a7d555",
        "on-primary-fixed-variant": "#354570",
        "on-tertiary-fixed-variant": "#314e2a",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#6d8c63",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dae2ff",
        "inverse-primary": "#b5c5f8",
        "outline": "#75777f",
        "outline-variant": "#c5c6d0",
        "inverse-surface": "#1e2f58",
        "on-surface": "#051942",
        "primary": "#000000",
        "secondary-fixed": "#c2f26e",
        "surface": "#faf8ff",
        "surface-container-low": "#f2f3ff",
        "on-primary-container": "#7283b1",
        "surface-bright": "#faf8ff",
        "primary-fixed-dim": "#b5c5f8",
        "on-surface-variant": "#45464e",
        "surface-tint": "#4d5d89",
        "tertiary": "#000000",
        "surface-container-highest": "#dae2ff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "on-tertiary-fixed": "#062104",
        "on-primary": "#ffffff",
        "secondary": "#486800",
        "on-secondary-container": "#4b6d00",
        "surface-container": "#eaedff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#caecbc",
        "error": "#ba1a1a",
        "secondary-container": "#bfef6b",
        "surface-dim": "#ced9ff",
        "inverse-on-surface": "#eef0ff",
        "on-primary-fixed": "#051942",
        "background": "#faf8ff",
        "surface-variant": "#dae2ff",
        "tertiary-container": "#062104",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#354e00",
        "tertiary-fixed-dim": "#aed0a1",
        "primary-container": "#051942",
        "on-secondary-fixed": "#131f00",
        "on-background": "#051942",
        "on-error": "#ffffff"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
